### ISSUE TITLE
Ruby 2.4.0 incompatibility

### ISSUE THREAD

**Issue by sethdeckard** [farrel/RCAP#7]
Hi,
In Ruby 2.4.0 `Fixnum` is depreciated and replaced with `Integer`.  Since this gem adds a `#blank?` method to `Fixnum`, the method will be missing in Ruby 2.4.0 since `#to_i` will then return an `Integer` rather than a `Fixnum`.

I guess the simple fix is to just add the `#blank?` method to `Integer` as well.  However, considering these methods always return false I was thinking we could just check the type of the object in the validation code instead and remove these `#blank?` methods.

Let me know what you think and I'll put together a PR.

**Comment by farrel** [comment]
Fixed in master, will be release in RCAP 2.7.0 shortly.

**Comment by sethdeckard** [comment]
Sounds great, thanks!
